# Generated by Django 4.2.2 on 2023-06-18 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='premiere',
            field=models.DateField(default=datetime.date.today, verbose_name='Премьера'),
        ),
    ]
